# Generated by Django 4.0 on 2023-04-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('version', models.CharField(max_length=10)),
                ('number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
