# Generated by Django 4.0 on 2023-04-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0008_student_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('short_name', models.CharField(max_length=10, null=True)),
                ('number', models.CharField(max_length=15)),
                ('address', models.TextField(null=True)),
            ],
        ),
    ]
