# Generated by Django 4.0 on 2023-04-26 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0009_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
